name: Publish the website

on:
  push:
    branches:
    - source

jobs:
  build-deploy:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
    - name: Build the website
      run: |
        ./build.sh
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: main
        publish_dir: ./build/
        force_orphan: true
